version: '3'

services:
  app_python:
    build: .
    image: usmanovdanil/devops_lab_1
    volumes:
      - /tmp:/tmp/logs
      - "appdata:/home/app/data"
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: '0.15'