---
# This playbook contains all actions that will be run on "local" host.

# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 86400  # One day
  tags:
    - setup

# Install dependencies
- name: Install main packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - vim
    - net-tools
    - curl
    - python3-pip

  tags:
    - setup

# Import docker tasks
- name: Import docker tasks
  include_tasks: install_docker.yml
  tags:
    - setup


# sudo apt-get autoclean
- name: Remove useless apt packages from the cache
  apt:
    autoclean: yes
  tags:
    - setup

# sudo apt-get autoremove
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - setup
