global:
  scrape_interval:     1s
  evaluation_interval: 1s
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']